- name: copy mongodb repo file
  ansible.builtin.include_role:
    name: common
    tasks_from: includemongorepofile

- name: install mongodb
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: search and replace in mongod.conf so other applications can access
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
    
- name: Restart service mongo in all cases
  ansible.builtin.service:
    name: mongod
    state: restarted