- name: install mongodb
  hosts: all,localhost
  become: yes
  tasks:
    - name: copy mongodb repo file
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: install mongodb
      ansible.builtin.yum:
        name: mongodb-org
        state: installed

    - name: search and replace in mongod.conf so other applications can access
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'
    
    - name: Restart service mongo in all cases
      ansible.builtin.service:
        name: mongod
        state: restarted
