- name: disable MYSQL. MYSQL 8 installed by default in centos. We need to install mysql5.7
  ansible.builtin.shell:
    yum module disable mysql -y

- name: copy mysql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d

- name: install mysql 5.7
  ansible.builtin.yum:
    name: mysql-community-server
    state: installed

- name: enable and restart mysql service
  ansible.builtin.systemd:
    name: mysqld
    enabled: true
    state: restarted

- name: Set MySQL root Password
  community.mysql.mysql_user:
    host: 'localhost'
    #login_user: 'root'
    #login_password: ''
    name: 'root'
    password: 'RoboShop@1'
    #state: present
