- name: Include nodejs file in catalogue
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs
# - name: Include nodejs file in catalogue
#   ansible.builtin.include_tasks:
#     file: nodejs.yml

- name: copy service file
  ansible.builtin.include_role:
    name: common
    tasks_from: copyservicefile

- name: start the catalogue service.
  ansible.builtin.include_role:
    name: common
    tasks_from: restartservice
# - name: reload the service so that server reads if any changes are done,restart catalogue
#   ansible.builtin.systemd:
#     state: restarted
#     daemon_reload: true
#     name: catalogue
#     enabled: true
 
- name: copy mongodb repo file
  ansible.builtin.include_role:
    name: common
    tasks_from: includemongorepo

- name: run the mongodb schema
  ansible.builtin.include_role:
   name: common
   tasks_from: runmongoschema

# - name: install mongodb client
#   ansible.builtin.yum:
#     name: mongodb-org-shell
#     state: installed

#     # - name: Run the catalogue schema to update the data in mongodb
#     #   community.mongodb.mongodb_shell:
#     #     login_host: mongodb.learnskill.fun
#     #     mongo_cmd: mongo
#     #     #quiet: true
#     #     file: "/app/schema/catalogue.js"
#     #     #idempotent: yes     

# - name: run the catalogue.js schema
#   ansible.builtin.shell:
#     mongo --host mongodb-dev.learnskill.fun </app/schema/catalogue.js