- name: Include nodejs file in catalogue
  ansible.builtin.include_role:
    name: common
    tasks_from: nodejs
# - name: Include nodejs file in catalogue
#   ansible.builtin.include_tasks:
#     file: nodejs.yml

- name: copy the configuration file
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: reload the service so that server reads if any changes are done,restart catalogue
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: catalogue
    enabled: true
 
<<<<<<< HEAD
- name: copy mongodb repo file
  ansible.builtin.include_role:
    name: common
    tasks_from: includemongorepofile
=======
# - name: copy mongodb repo file
#   ansible.builtin.copy:
#     src: mongodb.repo
#     dest: /etc/yum.repos.d/mongo.repo

- name: Include nodejs file in catalogue
  ansible.builtin.import_role:
    name: common
    tasks_from: includemongorepo.yml
>>>>>>> b47b791fefc632db5292e5d8b99041166ab6e3b5

- name: install mongodb client
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

    # - name: Run the catalogue schema to update the data in mongodb
    #   community.mongodb.mongodb_shell:
    #     login_host: mongodb.learnskill.fun
    #     mongo_cmd: mongo
    #     #quiet: true
    #     file: "/app/schema/catalogue.js"
    #     #idempotent: yes     

- name: run the catalogue.js schema
  ansible.builtin.shell:
    mongo --host mongodb-dev.learnskill.fun </app/schema/catalogue.js