- name: Restart service, in all cases, also issue daemon-reload to pick up config changes
  ansible.builtin.systemd:
    name: "{{component}}.service"
    daemon_reload: true
    enabled: true
    state: restarted