- name: install mongo shell
  ansible.builtin.yum:
    name: mongodb-org-shell
    state: installed

- name: run the schema
  ansible.builtin.shell:
    mongo --host mongodb-dev.learnskill.fun </app/schema/{{component}}.js